package kp.le.editor;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import kp.le.langfile.LanguageRepository.LineReference;
import kp.le.util.Utils;

/**
 *
 * @author Marc
 */
public class LineEdit extends JDialog
{
    private final LineEntry entry;
    private final LineReference line;
    
    private LineEdit(LineEntry entry)
    {
        super(entry.getEditor(), true);
        
        this.entry = entry;
        this.line = entry.getLine();
        
        initComponents();
        
        tTextArea.setLineWrap(true);
        
        switch(entry.getType())
        {
            case NORMAL -> setTitle("Text ID: " + entry.getId());
            case MESSAGE -> setTitle("Message ID: " + entry.getId());
            case LEVEL -> setTitle("Level ID: " + entry.getId());
        }
        
        fillText();
        pack();
        
        Utils.focus(this);
    }
    
    public static final void open(LineEntry entry)
    {
        var edit = new LineEdit(entry);
        edit.setVisible(true);
    }
    
    private void fillText()
    {
        var text = line.get();
        text = text.replace("<br>", "\n");
        
        tTextArea.setText(text);
    }
    
    private void saveText()
    {
        var text = tTextArea.getText();
        if(text.isBlank())
        {
            int opt = JOptionPane.showConfirmDialog(this, "The text is empty. Are you sure you want to continue?",
                    "Empty text warning", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if(opt != JOptionPane.YES_OPTION)
                return;
        }
        
        text = text.replace("\r", " ").replace("\n", "<br>");
        line.set(text);
        
        entry.getEditor().markAsModified();
        entry.update();
        entry.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bAccept = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        bApply = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bAccept.setText("Accept");
        bAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAcceptActionPerformed(evt);
            }
        });

        bCancel.setText("Cancel");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        bApply.setText("Apply");
        bApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bApplyActionPerformed(evt);
            }
        });

        tTextArea.setColumns(20);
        tTextArea.setRows(5);
        jScrollPane2.setViewportView(tTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 406, Short.MAX_VALUE)
                        .addComponent(bApply)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAccept)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAccept)
                    .addComponent(bCancel)
                    .addComponent(bApply))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        dispose();
    }//GEN-LAST:event_bCancelActionPerformed

    private void bApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bApplyActionPerformed
        saveText();
    }//GEN-LAST:event_bApplyActionPerformed

    private void bAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAcceptActionPerformed
        saveText();
        dispose();
    }//GEN-LAST:event_bAcceptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAccept;
    private javax.swing.JButton bApply;
    private javax.swing.JButton bCancel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea tTextArea;
    // End of variables declaration//GEN-END:variables
}
